### PR TITLE
Re-implement Pull Requests 1 & 2

### PR DESCRIPTION
**Pull request by Amadeus-**
Your latest commit overwrote the fixes I submitted with the first two pull requests:  

- https://github.com/Gator7778/ZGESO/pull/1
- https://github.com/Gator7778/ZGESO/pull/2

Those two pull requests just happen to involve files you must have just copied over from another place on your computer or something like that.

Anyway, merging this should re-implement those fixes and everything should be good again.

### CODE REVIEW

**Comment by Amadeus-** [comment]
I also noticed that you deleted a few files from the Guides directory.  Did you mean to do that?   If so, it's all good -- if not, just comment here if you need me to help fix anything as far as the repository goes.

**Comment by Gator7778** [comment]
i thought i left your fixes in there and yes im cleaning up the guide folder removing unused guides and going to redo the main quest guide will be easier than trying to fix it and add the rest of the quests

**Comment by Gator7778** [comment]
ill merge that once i finish the current guide im working on otherwise it may overwrite again.

**Comment by Amadeus-** [comment]
Sounds good!   Or, if you happen to edit/modify the files involved with this pull request, you can make the tweaks manually and then just close this without merging.  If you click on the "Files Changed" tab above, it's just 4 little edits across two files.

But yea, there's no rush -- I just wanted to do it while it was on my mind :)

**Comment by Amadeus-** [comment]
@Gator7778 I was also thinking that maybe you could enable "Discussions" on your repository here, so we have a place to discuss things, folks can ask questions, etc.   I haven't used it, but I'm sure it'll be better than setting up forums or a whole discord server for it.

I think it's under "Settings -> Options -> Features" ..then check click the "Discussions" checkbox.

**Comment by Gator7778** [comment]
ill do that and rename my discord server to help everyone since i already got an unused discord server

**Comment by Gator7778** [comment]
https://github.com/Gator7778/CLG/discussions/11
https://discord.gg/P4XpbeKHnK

**Review by Gator7778 — APPROVED** [review]

**Pull request merged**
